/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Form: typeof import('@primevue/forms/form')['default']
    GameGrid: typeof import('./src/components/GameGrid.vue')['default']
    GridRow: typeof import('./src/components/GridRow.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    Row: typeof import('primevue/row')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
